Python 3.8.10 (default, Nov 22 2023, 10:22:35) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
================= RESTART: /home/user/Aswin/python/Python70.py =================
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/user/Aswin/python/Python70.py", line 16, in <module>
    write = csv.write(file)
NameError: name 'csv' is not defined
>>> 
================= RESTART: /home/user/Aswin/python/Python70.py =================
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/user/Aswin/python/Python70.py", line 17, in <module>
    write = csv.write(file)
AttributeError: module 'csv' has no attribute 'write'
>>> 
================= RESTART: /home/user/Aswin/python/Python70.py =================
>>> 
>>> 
>>> 
>>> 
>>> 
>>> 
>>> 
>>> 
>>> 
>>> 
>>> 
>>> 
>>> 
>>> 
>>> 
>>> 
>>> 
>>> 
>>> 
>>> 
================= RESTART: /home/user/Aswin/python/Python70.py =================
>>> 
================= RESTART: /home/user/Aswin/python/Python71.py =================
>>> 
================= RESTART: /home/user/Aswin/python/Python71.py =================
['Name', 'Place', 'Age']
['Aswin', 'Amsterdam', '24']
['Anoop', 'London', '25']
>>> 
================= RESTART: /home/user/Aswin/python/Python71.py =================
['Name', 'Place', 'Age']
['Aswin', 'Amsterdam', '24']
['Anoop', 'London', '25']
>>> 
================= RESTART: /home/user/Aswin/python/Python71.py =================
['Name', 'Place', 'Age']
['Aswin', 'Amsterdam', '24']
['Anoop', 'London', '25']
>>> 
================= RESTART: /home/user/Aswin/python/Python71.py =================
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/user/Aswin/python/Python71.py", line 6, in <module>
    file = csv.reader(f) 
NameError: name 'csv' is not defined
>>> 
================= RESTART: /home/user/Aswin/python/Python71.py =================
['Name', 'Place', 'Age']
['Aswin', 'Amsterdam', '24']
['Anoop', 'London', '25']
>>> 
================= RESTART: /home/user/Aswin/python/Python72.py =================
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/user/Aswin/python/Python72.py", line 13, in <module>
    writer = csv.Dictwriteer(file,fieldname=fieldnames)
AttributeError: module 'csv' has no attribute 'Dictwriteer'
>>> 
>>> 
================= RESTART: /home/user/Aswin/python/Python72.py =================
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/user/Aswin/python/Python72.py", line 12, in <module>
    writer = csv.DictWriter(f,fieldnames=fields)
NameError: name 'fields' is not defined
>>> 
================= RESTART: /home/user/Aswin/python/Python72.py =================
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/user/Aswin/python/Python72.py", line 12, in <module>
    writer = csv.DictWriter(f,fieldnames=fields)
NameError: name 'fields' is not defined
>>> 
================= RESTART: /home/user/Aswin/python/Python72.py =================
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/user/Aswin/python/Python72.py", line 12, in <module>
    writer = csv.DictWriter(f,fieldnames=fields)
NameError: name 'fields' is not defined
>>> 
================= RESTART: /home/user/Aswin/python/Python72.py =================
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/user/Aswin/python/Python72.py", line 13, in <module>
    writer.writeheader()
  File "/usr/lib/python3.8/csv.py", line 142, in writeheader
    header = dict(zip(self.fieldnames, self.fieldnames))
TypeError: unhashable type: 'dict'
>>> 
================= RESTART: /home/user/Aswin/python/Python72.py =================
>>> 
================= RESTART: /home/user/Aswin/python/Python72.py =================
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/user/Aswin/python/Python72.py", line 8, in <module>
    {'Name':'Hari',Age:'23','Place': 'California'},
NameError: name 'Age' is not defined
>>> 
================= RESTART: /home/user/Aswin/python/Python72.py =================
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/user/Aswin/python/Python72.py", line 8, in <module>
    {'Name':'Hari',Age:'23','Place': 'California'},
NameError: name 'Age' is not defined
>>> 
================= RESTART: /home/user/Aswin/python/Python72.py =================
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/user/Aswin/python/Python72.py", line 8, in <module>
    {'Name':'Hari',Age:'23','Place': 'California'},
NameError: name 'Age' is not defined
>>> 
================= RESTART: /home/user/Aswin/python/Python72.py =================
>>> 
================= RESTART: /home/user/Aswin/python/Python73.py =================
Traceback (most recent call last):
  File "/usr/lib/python3.8/idlelib/run.py", line 559, in runcode
    exec(code, self.locals)
  File "/home/user/Aswin/python/Python73.py", line 5, in <module>
    with open('data.dict1.csv','r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'data.dict1.csv'
>>> 
================= RESTART: /home/user/Aswin/python/Python73.py =================
{'Name': 'Aswin', 'Age': '21', 'Place': 'London'}
{'Name': 'Hari', 'Age': '23', 'Place': 'California'}
{'Name': 'Anoop', 'Age': '24', 'Place': 'Amsterdam'}
>>> 